apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    app.kubernetes.io/managed-by: nullplatform
    app.kubernetes.io/part-of: hashicorp-vault-parameters-provider
